### Import Libraries

In [1]:
import glob
import pandas as pd
import os
import datetime
from Functions.py import *

ModuleNotFoundError: No module named 'Functions.py'; 'Functions' is not a package

### Specify the location to download the data

In [4]:
directory = os.getcwd()
# path for ECB portfolio data
url = directory[:-7] + "2. Data/1. ECB Data/Downloaded_Data - Web Scrapping/"
# path for bonds data
url_2 = directory[:-7] + "2. Data/2. Bonds Data - S&P/"
url_3 = directory[:-7] + "2. Data/2. Bonds Data - S&P/00_Company_Information/"

### Function for merging the downloaded data

In [7]:
def read_file_ecb(filename,url):
    data = pd.read_csv(url + filename,header = None,skiprows=1)
    #data.columns = columns
    year = filename[-12:-8]
    month = filename[-8:-6]
    day = filename[-6:-4]
    data['PUBLISHED_DATE'] = datetime.datetime(int(year),int(month),int(day))
    data['YEAR'] = year
    data['MONTH'] = month
    return data

def read_file_bonds(filename,url):
    data = pd.read_excel(url + filename,header = None,skiprows = 6)
    return data

def names_of_file(url):
    filelist = []
    os.chdir(url)
    for files in enumerate(glob.glob("*.csv")):
        filelist.append(files)
    return filelist

def bonds_file(url):
    filelist = []
    os.chdir(url)
    for files in enumerate(glob.glob("*.xlsx")):
        filelist.append(files)
    return filelist

### Merge the data

In [13]:
# ECB DATA 
data = []

files_ecb = names_of_file(url)

for f in files_ecb:
    data2 = read_file_ecb(f[1],url)
    data.append(data2)
    
data = pd.concat(data)

# Cleaning data 
ecb_data = data.drop(columns = [5,6])
columns = ['NCB','ISIN_CODE','ISSUER_NAME','MATURITY_DATE','COUPON_RATE','PUBLISHED_DATE','YEAR','MONTH']
ecb_data.columns = columns
ecb_data = ecb_data.dropna(axis = 0)
ecb_data.head()

,NCB,ISIN_CODE,ISSUER_NAME,MATURITY_DATE,COUPON_RATE,PUBLISHED_DATE,YEAR,MONTH
0,BE,BE0002178441,Delhaize Group S.A.,19/10/2018,4.25,2018-06-08,2018,06
1,BE,BE0002189554,Delhaize Group S.A.,27/02/2020,3.125,2018-06-08,2018,06
2,BE,BE0002239086,Elia System Operator S.A./N.V.,27/05/2024,1.375,2018-06-08,2018,06
3,BE,BE0002256254,RESA SA,22/07/2026,1,2018-06-08,2018,06
4,BE,BE0002269380,Cofinimmo S.A./N.V.,09/12/2024,2,2018-06-08,2018,06

In [24]:
# BONDS DATA
files_bonds = bonds_file(url_2)

data_2 = []
for f in files_bonds:
    data2 = read_file_bonds(f[1],url_2)
    data_2.append(data2)

data_2 = pd.concat(data_2)

columns = ['ISSUER_NAME','INSTRUMENT_ID','MI_KEY','CUSIP','DESCRIPTION','ISIN','AMT_OUTSTANDING','ISSUE_PRICE', 'ISSUE_AMOUNT','TOTAL_REVENUE'
          ,'TOTAL_DEBT','TOTAL_PREFERRED_EQUITY','TOTAL_COMMON_EQUITY','TOTAL_MINORITY_INTEREST','MARKET_CAPITALIZATION','MATURITY_DATE']

bonds_data = data_2.copy()
bonds_data.columns = columns
bonds_data.head()

,ISSUER_NAME,INSTRUMENT_ID,MI_KEY,CUSIP,DESCRIPTION,ISIN,AMT_OUTSTANDING,ISSUE_PRICE,ISSUE_AMOUNT,TOTAL_REVENUE,TOTAL_DEBT,TOTAL_PREFERRED_EQUITY,TOTAL_COMMON_EQUITY,TOTAL_MINORITY_INTEREST,MARKET_CAPITALIZATION,MATURITY_DATE
0,"""ArmSwissBank"" Closed Joint Stock Company",SPS677989702,4464605,NaN,3.5% BDS 01/06/2025 EUR100,AMSWISB2EER8,5795.757506,NaN,5795.757506,25754.70888,433436.564335,NaN,123813.283626,NaN,NaN,2025-06-01 00:00:00
1,1. Kassel Grundbesitz Gmbh,SPS678403632,22418525,NaN,0% BDS 01/07/2025 EUR,DE000A254UF0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-01 00:00:00
2,123 Invest Finanzgesellschaft mbH,SPS1764165131,9148311,NaN,4.15% BDS 31/12/2024 EUR1000,DE000A3MQNL3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-31 00:00:00
3,123 Invest Finanzgesellschaft mbH,SPS667281051,9148311,NaN,4.45% BDS 31/12/2024 EUR1000,DE000A254S17,5411.255411,NaN,5411.255411,NaN,NaN,NaN,NaN,NaN,NaN,2024-12-31 00:00:00
4,1more Project OU,SPS695552580,26488732,NaN,8% BDS 18/11/2026 EUR,EE3300001825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-11-18 00:00:00

In [11]:
# COMPANY INFORMATION DATA
files_info = bonds_file(url_3)

data_2 = []
for f in files_info:
    data2 = read_file_bonds(f[1],url_3)
    data_2.append(data2)

data_2 = pd.concat(data_2)
columns = ['ISSUER_NAME','INSTRUMENT_ID','ISIN','PARENT_COMPANY_NAME','ULTIMATE_PARENT_COMPANY','INDUSTRY_CLASSIFICATION','SIC_CODE','MATURITY_DATE']

info_data = data_2.copy()
info_data.columns = columns
info_data.head()

,ISSUER_NAME,INSTRUMENT_ID,ISIN,PARENT_COMPANY_NAME,ULTIMATE_PARENT_COMPANY,INDUSTRY_CLASSIFICATION,SIC_CODE,MATURITY_DATE
0,2Ab Management,SPS333860852,FR0013166550,NaN,NaN,Unclassified,NaN,2034-08-15
1,2i Rete Gas SpA,SPS702250617,XS2292547317,F2i Reti Italia S.r.l.,F2i Reti Italia S.r.l.,Gas Utilities,6719.0,2031-01-29
2,2Worlds S.R.L.,SPS572404182,IT0005337735,NaN,NaN,Unclassified,NaN,2037-01-30
3,2Worlds S.R.L.,SPS572404183,IT0005337743,NaN,NaN,Unclassified,NaN,2037-01-30
4,2Worlds S.R.L.,SPS572404184,IT0005337750,NaN,NaN,Unclassified,NaN,2037-01-30

## Combine ECB Data and Bonds Data

In [32]:
merge_bonds_info = bonds_data.merge(info_data, on = ['ISIN'])
merged_data = ecb_data.merge(merge_bonds_info,left_on =['ISIN_CODE'],right_on=['ISIN'],how = "left")
columns_to_keep = ['NCB','ISIN_CODE','ISSUER_NAME','MATURITY_DATE','COUPON_RATE','PUBLISHED_DATE','AMT_OUTSTANDING','ISSUE_PRICE','ISSUE_AMOUNT','TOTAL_REVENUE',
                  'PARENT_COMPANY_NAME','ULTIMATE_PARENT_COMPANY','INDUSTRY_CLASSIFICATION','SIC_CODE']

final_data = merged_data[columns_to_keep]

In [33]:
final_data.head()

,NCB,ISIN_CODE,ISSUER_NAME,MATURITY_DATE,COUPON_RATE,PUBLISHED_DATE,AMT_OUTSTANDING,ISSUE_PRICE,ISSUE_AMOUNT,TOTAL_REVENUE,PARENT_COMPANY_NAME,ULTIMATE_PARENT_COMPANY,INDUSTRY_CLASSIFICATION,SIC_CODE
0,BE,BE0002178441,Delhaize Group S.A.,19/10/2018,4.25,2018-06-08,NaN,101.867,345017.940933,2.707675e+07,NaN,NaN,Food Retail,5411.0
1,BE,BE0002189554,Delhaize Group S.A.,27/02/2020,3.125,2018-06-08,NaN,99.709,517263.675158,2.707675e+07,NaN,NaN,Food Retail,5411.0
2,BE,BE0002239086,Elia System Operator S.A./N.V.,27/05/2024,1.375,2018-06-08,529773.257046,99.835,529773.257046,9.797852e+05,NaN,NaN,Electric Utilities,1623.0
3,BE,BE0002256254,RESA SA,22/07/2026,1,2018-06-08,329236.172081,99.283,329236.172081,4.193494e+05,NaN,NaN,Multi-Utilities,4911.0
4,BE,BE0002269380,Cofinimmo S.A./N.V.,09/12/2024,2,2018-06-08,57937.427578,99.941,57937.427578,3.543690e+05,NaN,NaN,Diversified REIT,NaN

### Download the data

In [27]:
ecb_data.to_excel(directory[:-7] + '2. Data/1. ECB Data/ECB_Portfolio_2017_2022.xlsx',index = None)
bonds_data.to_excel(url_2 + 'Combined_Bonds_data.xlsx',index = None)
info_data.to_excel(url_3 + 'Company_Information_data.xlsx',index = None)

In [34]:
final_data.to_excel(directory[:-7] + "2. Data/Final_data.xlsx",index=None)