## Yearly Weighted Average Carbon Intensity (WACI)

<p>The WACI has two main components to it: emissions expressed as number of tonnes of CO2 equivalent and firms' million dollar revenue that is used to normalize the metric. The WACI is calculated yearly for every sector and country of risk by taking the average of monthly portfolio values and sectoral and country percentage breakdown. It is not calculate for individual firms as ECB does not publish the volume of each bonds' issue it purchases.  </p>

### Libraries to import

In [1]:
import pandas as pd
import os
from functions_file_3 import risk_country, yearly_waci_calculation_file,clean_master_file_yearly,yearly_mean_weighted_carbon_intensity, yearly_median_weighted_carbon_intensity, check_difference_waci,create_data,yearly_waci_sector_calculation,contribution_calculate
import warnings
warnings.filterwarnings("ignore")

In [2]:
directory = os.getcwd()
url = directory[:-7] + '2. Data/'

### Import datasets

In [3]:
master_file = pd.read_excel(url + 'Master_file.xlsx')

In [4]:
portfolio_value = pd.read_excel(url + '1. ECB Data/Portfolio_Breakdown_Information.xlsx',
                               sheet_name = 'Yearly_Portfolio_Value')
sector_breakdown = pd.read_excel(url + '1. ECB Data/Portfolio_Breakdown_Information.xlsx',
                               sheet_name = 'Yearly_Sector_Breakdown')
country_breakdown = pd.read_excel(url + '1. ECB Data/Portfolio_Breakdown_Information.xlsx',
                               sheet_name = 'Yearly_Country_Breakdown')

### Preprocessing

In [5]:
df = clean_master_file_yearly(master_file)

In [6]:
final_data = yearly_waci_calculation_file(df,portfolio_value,sector_breakdown,country_breakdown)
final_data = final_data.dropna()
final_data.head()

,YEAR,ECONOMIC_SECTOR,RISK_COUNTRY,MEAN_WEIGHTED_INTENSITY,MED_WEIGHTED_INTENSITY,TOTAL_HOLDINGS,TOTAL_HOLDINGS(USD),SECTOR_CSPP_HOLDINGS,SECTOR_ELIGIBLE_CSPP_UNIVERSE,COUNTRY_CSPP_HOLDINGS,COUNTRY_ELIGIBLE_CSPP_UNIVERSE
0,2017,Automotive and parts,Germany,10601.770000,10601.770000,114630.285714,120362,0.10,0.10,0.25,0.25
1,2017,Beverages,Belgium,61.359009,61.359009,114630.285714,120362,0.05,0.04,0.05,0.05
2,2017,Beverages,Germany,914.163404,7.803179,114630.285714,120362,0.05,0.04,0.25,0.25
3,2017,Beverages,Italy,143.184676,143.184676,114630.285714,120362,0.05,0.04,0.11,0.12
4,2017,Beverages,Netherlands,61.359009,61.359009,114630.285714,120362,0.05,0.04,0.06,0.05

### Yearly Sector WACI

In [7]:
df2 = yearly_waci_sector_calculation(df,portfolio_value,sector_breakdown)

In [8]:
yearly_sector_waci = contribution_calculate(df2)
yearly_sector_waci.head()

,YEAR,ECONOMIC_SECTOR,MEAN_WEIGHTED_INTENSITY,MED_WEIGHTED_INTENSITY,TOTAL_HOLDINGS,TOTAL_HOLDINGS(USD),SECTOR_CSPP_HOLDINGS,SECTOR_ELIGIBLE_CSPP_UNIVERSE,WEIGHTS,SUM_WEIGHTS,MEAN_WACI,MEDIAN_WACI,Contribution
0,2017,Automotive and parts,10601.770000,10601.770000,114630.285714,120362,0.10,0.10,0.10,0.91,1165.029670,1165.029670,0.2514
1,2017,Beverages,394.401688,42.700000,114630.285714,120362,0.05,0.04,0.05,0.91,21.670422,2.346154,0.0047
2,2017,Chemicals,2669.004984,22.663351,114630.285714,120362,0.05,0.04,0.05,0.91,146.648625,1.245239,0.0316
3,2017,Construction & Materials,182.510158,80.413680,114630.285714,120362,0.06,0.05,0.06,0.91,12.033637,5.302001,0.0026
4,2017,Energy and basic resources,322.410630,316.883348,114630.285714,120362,0.07,0.08,0.07,0.91,24.800818,24.375642,0.0054

### Yearly Mean WACI and Median WACI dataset

In [9]:
final_data['WEIGHTS'] = (final_data['SECTOR_CSPP_HOLDINGS']* final_data['COUNTRY_CSPP_HOLDINGS']*final_data['TOTAL_HOLDINGS(USD)'])/final_data['TOTAL_HOLDINGS(USD)']
final_data['SUM_WEIGHTS'] = final_data.groupby('YEAR')['WEIGHTS'].transform('sum')
final_data['MEAN_WACI'] = final_data['WEIGHTS']*final_data['MEAN_WEIGHTED_INTENSITY']/final_data['SUM_WEIGHTS']
final_data['MEDIAN_WACI'] = final_data['WEIGHTS']*final_data['MED_WEIGHTED_INTENSITY']/final_data['SUM_WEIGHTS']

In [10]:
columns_to_keep = ['YEAR','ECONOMIC_SECTOR','RISK_COUNTRY','MEAN_WACI','MEDIAN_WACI']
data = final_data[columns_to_keep]
data.head()

   YEAR       ECONOMIC_SECTOR RISK_COUNTRY   MEAN_WACI  MEDIAN_WACI
0  2017  Automotive and parts      Germany  402.374753   402.374753
1  2017             Beverages      Belgium    0.232879     0.232879
2  2017             Beverages      Germany   17.347871     0.148079
3  2017             Beverages        Italy    1.195561     1.195561
4  2017             Beverages  Netherlands    0.279455     0.279455

### Determine companies driving mean WACI

In [11]:
keys = [2017,2018,2019,2020,2021,2022]

df=[]
for k in keys:
    sector, condition = check_difference_waci(final_data,k)
    df2 = create_data(master_file,condition)
    df.append(df2)
    
new_data = pd.concat(df)

In [12]:
columns = ['Issuer Name','Risk Country','Economic Sector','Year','Number of bonds','Avg. Emission Intensity']
new_data.columns = columns

### Select a year

In [13]:
year = 2018

In [14]:
yearly_mean_weighted_carbon_intensity(year,final_data)

                                 MEAN_WACI                      \
ECONOMIC_SECTOR       Automotive and parts Beverages Chemicals
RISK_COUNTRY
Belgium                               0.00      0.24      3.46
France                                0.00      0.73      0.44
Germany                             345.26      6.14    142.01
Italy                                 0.00      1.37      0.00
Netherlands                           0.00      0.29      0.00
Other (euro area)                     0.00      0.00      0.00
Other (non-euro area)                 0.00      0.00      0.00
Spain                                 0.00      0.34      0.00

                                                                           \
ECONOMIC_SECTOR       Construction & Materials Energy and basic resources
RISK_COUNTRY
Belgium                                   0.00                       0.36
France                                    6.90                      11.60
Germany                                   1.88                       8.14
Italy                                     0.19                       5.56
Netherlands                               0.00                       0.78
Other (euro area)                         0.28                       2.43
Other (non-euro area)                     0.00                       0.00
Spain                                     0.00                       5.99

                                                                         \
ECONOMIC_SECTOR        Food Infrastructure and transportation Insurance
RISK_COUNTRY
Belgium                0.00                              0.00      0.00
France                 0.83                            126.19      0.01
Germany                0.26                              7.01      1.21
Italy                  0.00                              2.95      0.15
Netherlands            0.35                              1.94     16.87
Other (euro area)      0.00                              3.40      0.39
Other (non-euro area)  0.00                              0.00      0.00
Spain                  0.00                              1.34      0.01


ECONOMIC_SECTOR       Other sectors Real estate Telecommunication Utilities
RISK_COUNTRY
Belgium                        0.20        0.00              0.00     31.58
France                       236.58       62.46              1.08    225.01
Germany                       56.72        0.19              0.94     74.31
Italy                         14.87        0.90              0.45     13.92
Netherlands                  170.46        0.45              0.03    155.36
Other (euro area)           1081.29        0.52              1.15     32.36
Other (non-euro area)          0.15        0.00              0.00      0.00
Spain                         58.20        0.00              0.09      0.00

In [15]:
yearly_median_weighted_carbon_intensity(year,final_data)

                               MEDIAN_WACI                      \
ECONOMIC_SECTOR       Automotive and parts Beverages Chemicals
RISK_COUNTRY
Belgium                               0.00      0.24      3.46
France                                0.00      0.73      0.44
Germany                             345.26      0.16    172.63
Italy                                 0.00      1.37      0.00
Netherlands                           0.00      0.29      0.00
Other (euro area)                     0.00      0.00      0.00
Other (non-euro area)                 0.00      0.00      0.00
Spain                                 0.00      0.34      0.00

                                                                           \
ECONOMIC_SECTOR       Construction & Materials Energy and basic resources
RISK_COUNTRY
Belgium                                   0.00                       0.36
France                                    3.46                      11.60
Germany                                   1.88                       6.88
Italy                                     0.19                       5.56
Netherlands                               0.00                       0.38
Other (euro area)                         0.28                       2.58
Other (non-euro area)                     0.00                       0.00
Spain                                     0.00                       5.99

                                                                         \
ECONOMIC_SECTOR        Food Infrastructure and transportation Insurance
RISK_COUNTRY
Belgium                0.00                              0.00      0.00
France                 0.91                             17.02      0.01
Germany                0.25                              3.77      1.64
Italy                  0.00                              0.61      0.00
Netherlands            0.11                              3.40     27.87
Other (euro area)      0.00                              3.40      0.39
Other (non-euro area)  0.00                              0.00      0.00
Spain                  0.00                              1.34      0.01


ECONOMIC_SECTOR       Other sectors Real estate Telecommunication Utilities
RISK_COUNTRY
Belgium                        0.28        0.00              0.00     31.58
France                         5.89        2.26              1.17    119.99
Germany                        4.91        0.01              0.94     12.52
Italy                          2.36        0.90              0.45     13.35
Netherlands                   21.68        0.45              0.03     37.90
Other (euro area)              1.18        0.45              0.23     37.90
Other (non-euro area)          0.15        0.00              0.00      0.00
Spain                         40.62        0.00              0.09      0.00

### Download file

In [16]:
path = directory[:-7] + '2. Data/4. Dashboard Data/'
data.to_csv(path + 'WACI_data.csv',index = None)
final_data.to_csv(path + 'Final_data.csv',index=None)
new_data.to_csv(path + 'Data.csv',index = None)
yearly_sector_waci.to_csv(path + 'Yearly_sector_WACI')